export const cars = [
  {
    id: 1,
    name: 'Toyota Camry 2024',
    price: 40,
    type: 'Sedan',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Gasoline',
    image: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&auto=format&fit=crop',
    description: 'Надежный и комфортабельный седан для городских и загородных поездок. Идеально подходит для деловых встреч и семейных путешествий.',
    conditions: {
      minAge: 21,
      license: '2 years',
      deposit: 200,
    },
  },
  {
    id: 2,
    name: 'Honda CR-V 2024',
    price: 50,
    type: 'SUV',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Gasoline',
    image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&auto=format&fit=crop',
    description: 'Просторный и универсальный внедорожник, идеально подходящий для семейных поездок и приключений на природе.',
    conditions: {
      minAge: 23,
      license: '3 years',
      deposit: 300,
    },
  },

  {
    id: 5,
    name: 'Chevrolet Spark',
    price: 30,
    type: 'Economy',
    transmission: 'Automatic',
    seats: 4,
    fuel: 'Gasoline',
    image: 'https://www.google.com/url?sa=t&source=web&rct=j&url=https%3A%2F%2Faster.kz%2Fcars%2Fchevrolet%2Fspark&ved=0CBUQjRxqFwoTCMj73uex2JEDFQAAAAAdAAAAABAI&opi=89978449',
    description: 'Компактный и экономичный автомобиль для городских поездок. Отличный выбор для ежедневных дел по городу.',
    conditions: {
      minAge: 21,
      license: '2 years',
      deposit: 150,
    },
  },
  {
    id: 6,
    name: 'BMW X5 2024',
    price: 90,
    type: 'Premium',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Gasoline',
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&auto=format&fit=crop',
    description: 'Премиальный внедорожник с роскошным интерьером и мощным двигателем. Комфорт и престиж в одном автомобиле.',
    conditions: {
      minAge: 25,
      license: '5 years',
      deposit: 600,
    },
  },
  {
    id: 7,
    name: 'Mercedes-Benz C-Class',
    price: 75,
    type: 'Premium',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Gasoline',
    image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&auto=format&fit=crop',
    description: 'Элегантный седан премиум-класса с безупречным немецким качеством. Символ успеха и хорошего вкуса.',
    conditions: {
      minAge: 25,
      license: '5 years',
      deposit: 500,
    },
  },
  {
    id: 8,
    name: 'Audi A4 2024',
    price: 65,
    type: 'Premium',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Gasoline',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&auto=format&fit=crop',
    description: 'Спортивный премиальный седан с передовыми технологиями и динамичным дизайном. Удовольствие от вождения гарантировано.',
    conditions: {
      minAge: 23,
      license: '3 years',
      deposit: 400,
    },
  },
];
